"""`uparse generate` end to end: providers, the gate, and the file it writes."""

from __future__ import annotations

import json
import sys
import textwrap

import pytest
from click.testing import CliRunner

from uparse.assist import generate as run_generate
from uparse.assist.protocol import AssistError
from uparse.assist.providers import CommandProvider, OpenAICompatibleProvider
from uparse.cli import main
from uparse.config.schema import AssistConfig, Config
from uparse.core.models import PageModel
from uparse.sources.loader import normalize_url

# A stand-in model: reads the report, names the unnamed timestamp column, ignores UI text.
FAKE_MODEL = """
import json, re, sys
prompt = sys.stdin.read()
report = json.loads(re.search(r"<report>\\s*(\\{.*\\})\\s*</report>", prompt, re.S).group(1))
fields = []
for column in report["columns"]:
    sample = (column.get("samples") or [""])[0]
    if column.get("named"):
        fields.append({"name": column["named"], "column": column["id"], "why": "confirmed"})
    elif re.search(r"\\d+\\s+hrs?\\s+ago", sample):
        fields.append({"name": "published", "column": column["id"], "why": "relative timestamps"})
    elif sample and sample[0].isupper() and " " not in sample:
        fields.append({"name": "desk", "column": column["id"], "why": "one word per record"})
print("Certainly.\\n```json")
print(json.dumps({"fields": fields}))
print("```")
"""


@pytest.fixture
def fake_model(tmp_path):
    path = tmp_path / "fake_model.py"
    path.write_text(textwrap.dedent(FAKE_MODEL))
    return [sys.executable, str(path)]


@pytest.fixture
def run():
    def _run(*args):
        return CliRunner().invoke(main, list(args), catch_exceptions=False)

    return _run


def _config(command=None, **assist):
    settings = {"provider": "command", "command": command, "cache": False, **assist}
    return Config(
        acquirer="http",
        browser={"enabled": False},
        assist=AssistConfig(**settings) if command else AssistConfig(**assist),
    )


def _page(site_url, path="/obscured.html"):
    import httpx

    url = normalize_url(f"{site_url}{path}")
    return PageModel(url=url, final_url=url, html=httpx.get(url).text)


# --- the full loop --------------------------------------------------------


def test_a_model_names_a_column_the_engine_could_not(fake_model, site_url):
    result = run_generate(_page(site_url), _config(fake_model), want="title, published, desk")
    assert result.assisted
    names = [a.name for a in result.verdict.accepted]
    assert "published" in names  # span.sc-g7h8i9 — no class name to go on
    assert "desk" in names
    assert "title" in names


def test_fields_the_engine_already_finds_stay_auto(fake_model, site_url):
    result = run_generate(_page(site_url), _config(fake_model), want="title, published")
    assert '"title": "auto"' in result.jsonc
    assert '"published": { "selector": "span.sc-g7h8i9" }' in result.jsonc


def test_the_generated_file_explains_itself(fake_model, site_url):
    jsonc = run_generate(_page(site_url), _config(fake_model), want="title").jsonc
    assert jsonc.startswith("// Generated by `uparse generate`")
    assert "// Review before running." in jsonc
    assert "// confirmed" in jsonc


def test_the_generated_config_actually_runs(fake_model, site_url, tmp_path, run):
    job = tmp_path / "job.jsonc"
    out = tmp_path / "records.jsonl"
    jsonc = run_generate(_page(site_url), _config(fake_model), want="title, published").jsonc
    jsonc = jsonc.replace('"format": "csv"', '"format": "jsonl"').replace(
        '"./records.csv"', json.dumps(str(out))
    )
    job.write_text(jsonc)
    assert run(str(job), "--no-browser", "--no-pagination").exit_code == 0
    rows = [json.loads(line) for line in out.read_text().splitlines()]
    assert rows[0]["title"] == "Quantum Ledger Rewrites Banking"
    assert [r["published"] for r in rows] == ["3 hrs ago", "6 hrs ago", "9 hrs ago", "12 hrs ago"]
    assert [r["desk"] for r in rows] == ["Finance", "Science", "Transport", "Politics"]


# --- degrading rather than failing ----------------------------------------


def test_without_a_provider_the_engine_still_writes_a_config(site_url):
    result = run_generate(_page(site_url), _config(), want="title")
    assert not result.assisted
    assert "assist unavailable" in result.jsonc.lower()
    assert '"title": "auto"' in result.jsonc


def test_a_provider_that_fails_does_not_lose_the_file(site_url, tmp_path):
    missing = tmp_path / "nope.py"
    with pytest.raises(AssistError):
        CommandProvider(AssistConfig(provider="command", command=[str(missing)]))


def test_a_page_with_no_structure_is_reported_not_guessed(site_url):
    page = _page(site_url, "/empty.html")
    result = run_generate(page, _config())
    assert "no repeating structure" in (result.error or "")


def test_a_model_answering_with_prose_is_an_error_not_a_crash(tmp_path, site_url):
    babbler = tmp_path / "babble.py"
    babbler.write_text("print('I would rather not.')")
    result = run_generate(_page(site_url), _config([sys.executable, str(babbler)]), want="title")
    assert not result.assisted
    assert "JSON" in (result.error or "")


# --- the CLI --------------------------------------------------------------


def test_generate_writes_the_file_it_is_asked_for(run, site_url, tmp_path, fake_model):
    job = tmp_path / "job.jsonc"
    settings = tmp_path / "assist.jsonc"
    settings.write_text(
        json.dumps(
            {
                "acquirer": "http",
                "browser": {"enabled": False},
                "assist": {"provider": "command", "command": fake_model, "cache": False},
            }
        )
    )
    result = run(
        "generate",
        f"{site_url}/obscured.html",
        "-c",
        str(settings),
        "-o",
        str(job),
        "--want",
        "title, published",
    )
    assert result.exit_code == 0
    assert job.exists() and '"title"' in job.read_text()


def test_the_openai_driver_needs_a_base_url():
    with pytest.raises(AssistError):
        OpenAICompatibleProvider(AssistConfig.model_construct(provider="openai_compatible"))
