"""`uparse generate` end to end: providers, the gate, and the file it writes."""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
import time
from pathlib import Path

import httpx
import pytest
from click.testing import CliRunner

from uparse.assist import generate as run_generate
from uparse.assist.protocol import AssistError
from uparse.assist.providers import CommandProvider, OpenAICompatibleProvider
from uparse.cli import main
from uparse.config.schema import AssistConfig, Config
from uparse.core.models import PageModel
from uparse.sources.loader import normalize_url

# A stand-in model: reads the report, names the unnamed timestamp column, ignores UI text.
FAKE_MODEL = """
import json, re, sys
prompt = sys.stdin.read()
report = json.loads(re.search(r"<report>\\s*(\\{.*\\})\\s*</report>", prompt, re.S).group(1))
fields = []
for column in report["columns"]:
    sample = (column.get("samples") or [""])[0]
    if column.get("named"):
        fields.append({"name": column["named"], "column": column["id"], "why": "confirmed"})
    elif re.search(r"\\d+\\s+hrs?\\s+ago", sample):
        fields.append({"name": "published", "column": column["id"], "why": "relative timestamps"})
    elif sample and sample[0].isupper() and " " not in sample:
        fields.append({"name": "desk", "column": column["id"], "why": "one word per record"})
print("Certainly.\\n```json")
print(json.dumps({"fields": fields}))
print("```")
"""


@pytest.fixture
def fake_model(tmp_path):
    path = tmp_path / "fake_model.py"
    path.write_text(textwrap.dedent(FAKE_MODEL))
    return [sys.executable, str(path)]


@pytest.fixture
def run():
    def _run(*args):
        return CliRunner().invoke(main, list(args), catch_exceptions=False)

    return _run


def _config(command=None, **assist):
    settings = {"provider": "command", "command": command, "cache": False, **assist}
    return Config(
        acquirer="http",
        browser={"enabled": False},
        assist=AssistConfig(**settings) if command else AssistConfig(**assist),
    )


def _page(site_url, path="/obscured.html"):
    import httpx

    url = normalize_url(f"{site_url}{path}")
    return PageModel(url=url, final_url=url, html=httpx.get(url).text)


# --- the full loop --------------------------------------------------------


def test_a_model_names_a_column_the_engine_could_not(fake_model, site_url):
    result = run_generate(_page(site_url), _config(fake_model), want="title, published, desk")
    assert result.assisted
    names = [a.name for a in result.verdict.accepted]
    assert "published" in names  # span.sc-g7h8i9 — no class name to go on
    assert "desk" in names
    assert "title" in names


def test_fields_the_engine_already_finds_stay_auto(fake_model, site_url):
    result = run_generate(_page(site_url), _config(fake_model), want="title, published")
    assert '"title": "auto"' in result.jsonc
    assert '"published": { "selector": "span.sc-g7h8i9" }' in result.jsonc


def test_the_generated_file_explains_itself(fake_model, site_url):
    jsonc = run_generate(_page(site_url), _config(fake_model), want="title").jsonc
    assert jsonc.startswith("// Generated by `uparse generate`")
    assert "// Review before running." in jsonc
    assert "// confirmed" in jsonc


def test_the_generated_config_actually_runs(fake_model, site_url, tmp_path, run):
    job = tmp_path / "job.jsonc"
    out = tmp_path / "records.jsonl"
    jsonc = run_generate(_page(site_url), _config(fake_model), want="title, published").jsonc
    jsonc = jsonc.replace('"format": "csv"', '"format": "jsonl"').replace(
        '"./records.csv"', json.dumps(str(out))
    )
    job.write_text(jsonc)
    assert run(str(job), "--no-browser", "--no-pagination").exit_code == 0
    rows = [json.loads(line) for line in out.read_text().splitlines()]
    assert rows[0]["title"] == "Quantum Ledger Rewrites Banking"
    assert [r["published"] for r in rows] == ["3 hrs ago", "6 hrs ago", "9 hrs ago", "12 hrs ago"]
    assert [r["desk"] for r in rows] == ["Finance", "Science", "Transport", "Politics"]


# --- degrading rather than failing ----------------------------------------


def test_without_a_provider_the_engine_still_writes_a_config(site_url):
    result = run_generate(_page(site_url), _config(), want="title")
    assert not result.assisted
    assert "assist unavailable" in result.jsonc.lower()
    assert '"title": "auto"' in result.jsonc


def test_a_provider_that_fails_does_not_lose_the_file(site_url, tmp_path):
    missing = tmp_path / "nope.py"
    with pytest.raises(AssistError):
        CommandProvider(AssistConfig(provider="command", command=[str(missing)]))


def test_a_page_with_no_structure_is_reported_not_guessed(site_url):
    page = _page(site_url, "/empty.html")
    result = run_generate(page, _config())
    assert "no repeating structure" in (result.error or "")


def test_a_model_answering_with_prose_is_an_error_not_a_crash(tmp_path, site_url):
    babbler = tmp_path / "babble.py"
    babbler.write_text("print('I would rather not.')")
    result = run_generate(_page(site_url), _config([sys.executable, str(babbler)]), want="title")
    assert not result.assisted
    assert "JSON" in (result.error or "")


# --- the CLI --------------------------------------------------------------


def test_generate_writes_the_file_it_is_asked_for(run, site_url, tmp_path, fake_model):
    job = tmp_path / "job.jsonc"
    settings = tmp_path / "assist.jsonc"
    settings.write_text(
        json.dumps(
            {
                "acquirer": "http",
                "browser": {"enabled": False},
                "assist": {"provider": "command", "command": fake_model, "cache": False},
            }
        )
    )
    result = run(
        "generate",
        f"{site_url}/obscured.html",
        "-c",
        str(settings),
        "-o",
        str(job),
        "--want",
        "title, published",
    )
    assert result.exit_code == 0
    assert job.exists() and '"title"' in job.read_text()


def test_the_openai_driver_needs_a_base_url():
    with pytest.raises(AssistError):
        OpenAICompatibleProvider(AssistConfig.model_construct(provider="openai_compatible"))


# --- the page is hostile --------------------------------------------------


INJECTION = """
import json, sys
sys.stdin.read()
print(json.dumps({"fields": [
    {"name": "published", "column": "c2",
     "why": "fine\\n  \\"exfiltrate\\": { \\"selector\\": \\"body\\" },\\n  \\"x\\": \\""},
]}))
"""


@pytest.fixture
def injecting_model(tmp_path):
    path = tmp_path / "injecting.py"
    path.write_text(textwrap.dedent(INJECTION))
    return [sys.executable, str(path)]


def test_a_newline_in_the_model_s_answer_cannot_write_json(injecting_model, site_url):
    """The comment is where model text lands, and a newline there would end the comment and
    begin a line of config. Blast radius has to stay 'a bad name in a file you review'."""
    import json as jsonlib

    from uparse.config.jsonc import loads

    jsonc = run_generate(_page(site_url), _config(injecting_model), want="published").jsonc
    parsed = loads(jsonc)
    assert "exfiltrate" not in jsonlib.dumps(parsed)
    assert all(line.count("\n") == 0 for line in jsonc.splitlines())


def test_a_field_name_from_the_page_cannot_reshape_the_file(site_url, tmp_path):
    from uparse.config.jsonc import loads

    hostile = tmp_path / "hostile.py"
    hostile.write_text(
        'import json,sys; sys.stdin.read(); print(json.dumps({"fields": ['
        '{"name": "a\\": \\"auto\\", \\"b", "column": "c1"}]}))'
    )
    jsonc = run_generate(_page(site_url), _config([sys.executable, str(hostile)])).jsonc
    assert "b" not in loads(jsonc)["extraction"]["fields"]


# --- degrading, retrying, backing off -------------------------------------


REPAIRABLE = """
import json, os, sys
sys.stdin.read()
marker = os.environ["MARKER"]
if os.path.exists(marker):
    print(json.dumps({"fields": [{"name": "published", "column": "c2"}]}))
else:
    open(marker, "w").close()
    print("I would rather describe it in words.")
"""


def test_a_text_provider_gets_one_repair_attempt(tmp_path, site_url, monkeypatch):
    script = tmp_path / "repairable.py"
    script.write_text(textwrap.dedent(REPAIRABLE))
    monkeypatch.setenv("MARKER", str(tmp_path / "asked-once"))
    result = run_generate(
        _page(site_url), _config([sys.executable, str(script)], tier="text"), want="published"
    )
    assert result.assisted


def test_the_command_provider_never_runs_in_the_user_s_directory(tmp_path, site_url):
    """opencode and friends read whatever project they start in — slow, and the wrong
    blast radius for a prompt built from an untrusted page."""
    script = tmp_path / "pwd.py"
    script.write_text(
        'import json,os,sys; sys.stdin.read(); print(json.dumps({"cwd": os.getcwd()}))'
    )
    provider = CommandProvider(
        AssistConfig(provider="command", command=[sys.executable, str(script)])
    )
    where = json.loads(provider.complete("s", "u", {}))["cwd"]
    assert Path(where).resolve() != Path.cwd().resolve()


def test_a_rate_limited_provider_backs_off_then_says_who_limited_it(monkeypatch):
    from uparse.assist import providers

    monkeypatch.setattr(providers, "MAX_BACKOFF_S", 0.0)
    calls = []

    def limited(url, **kwargs):
        calls.append(url)
        return httpx.Response(
            429, headers={"retry-after": "120"}, request=httpx.Request("POST", url)
        )

    monkeypatch.setattr(providers.httpx, "post", limited)
    provider = providers.OpenAICompatibleProvider(
        AssistConfig(provider="openai_compatible", base_url="https://x.test/v1")
    )
    with pytest.raises(AssistError, match="rate limited"):
        provider.complete("s", "u", {})
    assert len(calls) == providers.RATE_LIMIT_ATTEMPTS


def test_an_answer_that_names_no_column_is_reported(tmp_path, site_url):
    script = tmp_path / "shrug.py"
    script.write_text('import sys; sys.stdin.read(); print(\'{"summary": "a shop page"}\')')
    result = run_generate(_page(site_url), _config([sys.executable, str(script)]))
    assert "named no column" in (result.error or "")


# A tool that starts a server and talks to it — the shape opencode and friends have.
ORPHANING = """
import subprocess, sys, time
subprocess.Popen([sys.executable, "-c", "import time; time.sleep(120)  # UPARSE_ORPHAN_MARK"])
time.sleep(120)
"""


def test_a_timed_out_tool_does_not_leave_its_server_running(tmp_path):
    script = tmp_path / "orphaning.py"
    script.write_text(textwrap.dedent(ORPHANING))
    provider = CommandProvider(
        AssistConfig(provider="command", command=[sys.executable, str(script)], timeout_s=2)
    )
    started = time.monotonic()
    try:
        with pytest.raises(AssistError, match="no answer within"):
            provider.complete("s", "u", {})
        assert time.monotonic() - started < 20
        found = subprocess.run(
            ["pgrep", "-f", "UPARSE_ORPHAN_MARK"], capture_output=True, text=True
        )
        assert not found.stdout.split(), "the tool's own child outlived the timeout"
    finally:
        subprocess.run(["pkill", "-f", "UPARSE_ORPHAN_MARK"], capture_output=True)


# --- the OpenAI-compatible driver -----------------------------------------


@pytest.fixture
def captured(monkeypatch):
    """Answer any chat completion, and hand back what we were asked to send."""
    from uparse.assist import providers

    sent: dict[str, object] = {}

    def post(url, *, json=None, headers=None, timeout=None):
        sent.update(url=url, payload=json, headers=headers)
        return httpx.Response(
            200,
            json={"choices": [{"message": {"content": '{"fields": []}'}}]},
            request=httpx.Request("POST", url),
        )

    monkeypatch.setattr(providers.httpx, "post", post)
    return sent


def _openai(**assist):
    from uparse.assist import providers

    return providers.OpenAICompatibleProvider(
        AssistConfig(provider="openai_compatible", base_url="https://x.test/v1/", **assist)
    )


@pytest.mark.parametrize(
    ("tier", "want"),
    [("schema", "json_schema"), ("json", "json_object"), ("text", None)],
)
def test_the_answer_is_asked_for_as_precisely_as_the_provider_allows(captured, tier, want):
    _openai(tier=tier).complete("s", "u", {"type": "object"})
    fmt = captured["payload"].get("response_format")
    assert (fmt or {}).get("type") == want
    assert captured["url"] == "https://x.test/v1/chat/completions"


def test_the_key_comes_from_the_environment(captured, monkeypatch):
    monkeypatch.setenv("SOME_PROVIDER_KEY", "sk-secret")
    _openai(api_key_env="SOME_PROVIDER_KEY").complete("s", "u", {})
    assert captured["headers"]["Authorization"] == "Bearer sk-secret"


def test_no_key_env_means_no_authorization_header(captured):
    _openai().complete("s", "u", {})
    assert "Authorization" not in captured["headers"]


def test_content_returned_in_parts_is_joined(monkeypatch):
    from uparse.assist import providers

    monkeypatch.setattr(
        providers.httpx,
        "post",
        lambda url, **kw: httpx.Response(
            200,
            json={"choices": [{"message": {"content": [{"text": "{"}, {"text": '"a": 1}'}]}}]},
            request=httpx.Request("POST", url),
        ),
    )
    assert _openai().complete("s", "u", {}) == '{"a": 1}'


def test_a_failing_provider_names_itself(monkeypatch):
    from uparse.assist import providers

    monkeypatch.setattr(
        providers.httpx,
        "post",
        lambda url, **kw: httpx.Response(
            503, text="upstream down", request=httpx.Request("POST", url)
        ),
    )
    with pytest.raises(AssistError, match=r"openai_compatible:.*503"):
        _openai().complete("s", "u", {})


# --- the cache ------------------------------------------------------------


COUNTING = """
import json, os, sys
sys.stdin.read()
tally = os.environ["TALLY"]
n = (int(open(tally).read()) if os.path.exists(tally) else 0) + 1
open(tally, "w").write(str(n))
print(json.dumps({"fields": [{"name": "published", "column": "c2"}]}))
"""


def test_asking_twice_about_the_same_page_calls_the_model_once(tmp_path, site_url, monkeypatch):
    """A free tier is 100-1,000 requests a day. Re-running `generate` on a page already
    analysed must not spend one of them."""
    generate_mod = sys.modules["uparse.assist.generate"]

    script = tmp_path / "counting.py"
    script.write_text(textwrap.dedent(COUNTING))
    tally = tmp_path / "calls"
    monkeypatch.setenv("TALLY", str(tally))
    monkeypatch.setattr(generate_mod, "CACHE_DIR", tmp_path / "cache")

    page = _page(site_url)
    config = _config([sys.executable, str(script)], cache=True)
    first = run_generate(page, config, want="published")
    second = run_generate(page, config, want="published")

    assert first.assisted and second.assisted
    assert not first.cached and second.cached
    assert tally.read_text() == "1"
    assert first.jsonc == second.jsonc


def test_a_read_only_cache_directory_does_not_fail_the_run(tmp_path, site_url, monkeypatch):
    generate_mod = sys.modules["uparse.assist.generate"]

    script = tmp_path / "counting.py"
    script.write_text(textwrap.dedent(COUNTING))
    monkeypatch.setenv("TALLY", str(tmp_path / "calls"))
    blocked = tmp_path / "blocked"
    blocked.write_text("not a directory")
    monkeypatch.setattr(generate_mod, "CACHE_DIR", blocked / "cache")

    result = run_generate(
        _page(site_url), _config([sys.executable, str(script)], cache=True), want="published"
    )
    assert result.assisted and not result.cached
