"""Turn a page plus an intent into a reviewable job file.

    acquire → extract → brief → propose → validate → job.jsonc → a human → run

The model's part is the third arrow only. Everything the generated config does at run time
is deterministic, and the file itself is the deliverable: readable, diffable, and free of
any dependency on the model that suggested it.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from uparse.assist import prompt as prompts
from uparse.assist.brief import PageBrief
from uparse.assist.brief import build as build_brief
from uparse.assist.protocol import AssistError, Proposal, Provider, parse_payload
from uparse.assist.providers import build as build_provider
from uparse.assist.validate import Verdict, check
from uparse.config.schema import Config
from uparse.core.models import PageModel
from uparse.extraction.engine import ExtractionResult, extract
from uparse.logging import get_logger

log = get_logger("assist")

CACHE_DIR = Path.home() / ".cache" / "uparse" / "assist"


@dataclass(slots=True)
class Generated:
    brief: PageBrief
    verdict: Verdict
    jsonc: str
    provider: str
    cached: bool = False
    error: str | None = None

    @property
    def assisted(self) -> bool:
        return self.error is None and self.verdict.ok


def generate(
    page: PageModel, config: Config, *, want: str | None = None, cache: bool | None = None
) -> Generated:
    result = extract(page, config.extraction)
    brief = build_brief(page, result)

    verdict = Verdict(accepted=[], rejected=[])
    provider_name = "null"
    cached = False
    error: str | None = None

    if not brief.has_material:
        error = "the engine found no repeating structure on this page"
    else:
        try:
            provider = build_provider(config.assist)
            provider_name = getattr(provider, "name", "unknown")
            proposal, cached = _propose(
                provider,
                brief,
                want,
                use_cache=config.assist.cache if cache is None else cache,
            )
            verdict = check(
                proposal,
                brief,
                result.records,
                min_coverage=config.assist.min_coverage,
                max_fields=config.assist.max_fields,
            )
        except AssistError as exc:
            error = str(exc)
            log.debug("assist unavailable: %s", exc)

    return Generated(
        brief=brief,
        verdict=verdict,
        jsonc=render(page, config, brief, verdict, result, want=want, error=error),
        provider=provider_name,
        cached=cached,
        error=error,
    )


def _propose(
    provider: Provider, brief: PageBrief, want: str | None, *, use_cache: bool
) -> tuple[Proposal, bool]:
    key = _cache_key(provider, brief, want)
    if use_cache:
        hit = _cache_read(key)
        if hit is not None:
            log.debug("assist cache hit %s", key[:12])
            return Proposal.from_payload(hit), True

    answer = provider.complete(prompts.system(), prompts.user(brief, want), prompts.SCHEMA)
    payload = parse_payload(answer)
    if use_cache:
        _cache_write(key, payload)
    return Proposal.from_payload(payload), False


# ------------------------------------------------------------------ output


def render(
    page: PageModel,
    config: Config,
    brief: PageBrief,
    verdict: Verdict,
    result: ExtractionResult,
    *,
    want: str | None = None,
    error: str | None = None,
) -> str:
    """Emit JSONC. Comments are the point: the file has to explain why it says what it says."""
    stamp = datetime.now(UTC).strftime("%Y-%m-%d")
    lines: list[str] = [
        f"// Generated by `uparse generate` on {stamp}.",
        f"// Source: {page.base_url}",
        f"// Engine: strategy {result.strategy}, {len(result.records)} records.",
    ]
    if want:
        lines.append(f"// Asked for: {want}")
    if error:
        lines.append(f"// Assist unavailable ({error}) — fields below are the engine's own.")
    for item in verdict.rejected:
        lines.append(f"// Dropped {item.name!r}: {item.reason}.")
    lines += ["// Review before running.", "{"]

    lines.append('  "sources": {')
    lines.append('    "type": "url",')
    lines.append(f'    "url": {json.dumps(page.base_url)}')
    lines.append("  },")
    lines.append("")

    if config.acquirer != "auto":
        lines.append(f'  "acquirer": {json.dumps(config.acquirer)},')
    lines.append('  "extraction": {')
    if verdict.collection:
        lines.append(f'    "collection": {json.dumps(verdict.collection)},')
    lines.append('    "fields": {')
    lines += _fields(verdict, result)
    lines.append("    }")
    lines.append("  },")
    lines.append("")
    lines.append('  "output": {')
    lines.append('    "format": "csv",')
    lines.append('    "path": "./records.csv"')
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _fields(verdict: Verdict, result: ExtractionResult) -> list[str]:
    entries: list[tuple[str, str, str]] = []
    for item in verdict.accepted:
        # Pin a selector only where it adds something. When the model simply confirms a
        # name the engine already produces, "auto" keeps every refinement the engine
        # applies to that value — ellipsis recovery, absolutization, type coercion.
        if item.agrees_with_engine or item.selector.startswith("(field:"):
            spec, note = '"auto"', item.why or "the engine already finds this"
        else:
            spec = f'{{ "selector": {json.dumps(item.selector)} }}'
            note = item.why or f"{item.coverage:.0%} of records, e.g. {item.sample[:40]!r}"
        entries.append((item.name, spec, note))

    if not entries:  # no model, or nothing survived: fall back to what the engine named
        for name in result.schema:
            entries.append((name, '"auto"', "inferred by the engine"))

    out: list[str] = []
    for index, (name, spec, note) in enumerate(entries):
        comma = "," if index < len(entries) - 1 else ""
        out.append(f"      {json.dumps(name)}: {spec}{comma}  // {note}")
    return out


# ------------------------------------------------------------------- cache


def _cache_key(provider: Provider, brief: PageBrief, want: str | None) -> str:
    blob = "\x00".join([getattr(provider, "name", "?"), brief.to_json(), want or ""])
    return hashlib.sha256(blob.encode("utf-8", "replace")).hexdigest()


def _cache_read(key: str) -> dict[str, Any] | None:
    path = CACHE_DIR / f"{key}.json"
    try:
        return dict(json.loads(path.read_text(encoding="utf-8")))
    except OSError, ValueError:
        return None


def _cache_write(key: str, payload: dict[str, Any]) -> None:
    try:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        (CACHE_DIR / f"{key}.json").write_text(
            json.dumps(payload, ensure_ascii=False), encoding="utf-8"
        )
    except OSError as exc:  # a read-only home must not fail a run
        log.debug("cannot cache proposal: %s", exc)
